base_url = "https://mort.io"

title = "mort's mythopœia"
description = "with apologies"

theme = "abridge"
default_language = "en"

compile_sass = true
minify_html = true
build_search_index = false

generate_feed = true
taxonomies = [{ name = "tags", feed = true }]
feed_filename = "atom.xml"

[markdown]
highlight_code = true
highlight_theme = "css"
render_emoji = true
smart_punctuation = true

[extra]

menu = [
    { url = "research", name = "research", slash = true, blank = false, size = "s110" },
    { url = "teaching", name = "teaching", slash = true, blank = false, size = "s110" },
    { url = "codes", name = "codes", slash = true, blank = false, size = "s110" },
    { url = "me", name = "me", slash = true, blank = false, size = "s110" },
]
menu_footer = [
    { url = "sitemap.xml", name = "sitemap", slash = false, blank = true },
]

toc = true
recent = true
recent_items = 12
series = true
series_items = 9

meta_index = { position = "bottom", size = "s90", author = false, readtime = false, readstring = "min", date = true, updated = false, categories_tags = true, divider = "" }
meta_post = { position = "top", size = "s95", author = true, readtime = false, readstring = "min read", date = true, updated = true, categories_tags = true, divider = "" }

hide_section_dates = false        # hides the date for sections that use posts.html as their template.
hide_page_nextprev_titles = false # hides the next/previous titles for pages that use page.html as their template.
title_size_index = "s85"
footer_size = "s90"
footer_credit = false

sitedesc = true
headhr = true
foothr = true

copyright_override = '$SITE_TITLE © 2013-$CURRENT_YEAR Richard Mortier'

title_separator = "|" 
author = "Richard Mortier"
twitter_meta = "mor1"
seo = true

# need also to configure icons in sass/abridge.scss
feed = true
mail = "richard.mortier@cl.cam.ac.uk"
mail_encode = false
mastodon = "@mort@mastodon.me.uk"
twitter = "mort___"
# linkedin = "your-user-name"
github = "mor1"
docker = "mor1"

uglyurls = false # if set to true then links are generated with the full path. eg https://abridge.netlify.app/index.html
integrity = true # increases site security, should normally be true. (setting to false is useful during js development)

# ...plus build_search_index=false above, disable javascript
js_bundle = false
js_copycode = false
js_email_encode = false
js_prestyle = false
js_switcher = false
pwa = false

favicon_theme_color = "#333333"
favicon_ms_color = "#333333"
favicon_mask = "safari-pinned-tab.svg" # safari-pinned-tab.svg
favicon_mask_color = "#ff9900"
favicon_svg = "favicon.svg"            # favicon.svg
favicon180 = "apple-touch-icon.png"    # apple-touch-icon.png
favicon32 = "favicon-32x32.png"        # favicon-32x32.png
favicon16 = "favicon-16x16.png"        # favicon-16x16.png
